
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  producer:
    build:
      context: .
      dockerfile: kafka/producer/Dockerfile
    depends_on:
      - kafka
    restart: always
    env_file:
      - ./.env

  consumer:
    build:
      context: .
      dockerfile: kafka/consumer/Dockerfile
    depends_on:
      - kafka
    restart: always
    env_file:
      - ./.env

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"